apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: nationalparks
  name: nationalparks
spec:
  triggers:
    - type: "ConfigChange"
  output:
    to:
      kind: ImageStreamTag
      name: nationalparks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: nationalparks
    git:
      ref: master
      uri: http://gogs-mitzicom-poc-cicd.apps.na37.openshift.opentlc.com/mc/parks
    sourceSecret:
      name: gogs-repo-secret
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.2
        namespace: openshift
    type: Source