apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: parks
  name: parks
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: parks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: parksmap
    git:
      uri: http://gogs-mitzicom-poc-cicd.apps.na37.openshift.opentlc.com/mc/parks.git
    sourceSecret:
      name: gogs-repo-secret
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.2
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 4gqdevhqGxdmBbgg533L
    type: GitHub
  - generic:
      secret: bsRTktyk3_Wp74SmJaNx
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0