apiVersion: v1
kind: Template
metadata:
  name: parks
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: parks
    name: parks
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: parks
      deploymentconfig: parks
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: parks
          deploymentconfig: parks
      spec:
        containers:
        - image: docker-registry.default.svc:5000/mitzicom-poc-dev/parks:latest
          imagePullPolicy: Always
          name: parks
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - parks
        from:
          kind: ImageStreamTag
          name: parks:latest
          namespace: mitzicom-poc-dev
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: parks
    name: parks
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: parks
      deploymentconfig: parks
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: parks
    name: parks
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: parks
      weight: 100
    wildcardPolicy: None
