apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongodb
    template: mongodb-persistent-template
  name: mongodb-configmap
type: Opaque
data:
  database-admin-password: password
  database-name: maps
  database-password: password
  database-user: user
  database-host: mongodb
  database-port: "27017"
  database-rs: rs0
  database-keyfile: "12345678901234567890"
  service-name: mongodb
