apiVersion: v1
kind: Template
metadata:
  name: mongodb-persistent-replicaset
objects:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: "mongodb"
  spec:
    serviceName: "mongodb-internal"
    replicas: 3
    template:
      metadata:
        labels:
          name: "mongodb"
      spec:
        containers:
          - name: mongo-container
            image: "registry.access.redhat.com/rhscl/mongodb-32-rhel7:3.2"
            ports:
              - containerPort: 27017
            args:
              - "run-mongod-replication"
            volumeMounts:
              - name: mongo-data
                mountPath: "/var/lib/mongodb/data"
            env:
              - name: MONGODB_DATABASE
                value: ${MONGODB_DATABASE}
              - name: MONGODB_USER
                value: ${MONGODB_USER}
              - name: MONGODB_PASSWORD
                value: ${MONGODB_PASSWORD}
              - name: MONGODB_ADMIN_PASSWORD
                value: ${MONGODB_ADMIN_PASSWORD}
              - name: MONGODB_REPLICA_NAME
                value: ${MONGODB_REPLICA_NAME}
              - name: MONGODB_KEYFILE_VALUE
                value: ${MONGODB_KEYFILE_VALUE}
              - name: MONGODB_SERVICE_NAME
                value: ${MONGODB_SERVICE_NAME}
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: mongo-data
          labels:
            name: "mongodb"
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: ${MONGODB_VOLUME_CAPACITY}
- apiVersion: v1
  kind: Service
  metadata:
    name: "mongodb-internal"
    labels:
      name: "mongodb"
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    clusterIP: None
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: "mongodb"
parameters:
- description: Volume space available for MongoDB, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: MONGODB_VOLUME_CAPACITY
  required: true
  value: 4Gi
- description: Mongodb user name
  displayName: Mongodb user name
  name: MONGODB_USER
  required: true
  value: mongodb_user
- description: Mongodb password
  displayName: Mongodb password
  name: mongodb_password
  required: true
  value: Test123456
- description: Mongodb Admin password
  displayName: Mongodb Admin password
  name: MONGODB_ADMIN_PASSWORD
  required: true
  value: Test123456
- description: Mongodb database
  displayName: Mongodb database
  name: MONGODB_DATABASE
  required: true
  value: mongodb
- description: Mongodb replicaset name
  displayName: Mongodb replicaset name
  name: MONGODB_REPLICA_NAME
  required: true
  value: "rs0"  
- description: Mongodb keyfile value
  displayName: Mongodb keyfile value
  name: MONGODB_KEYFILE_VALUE
  required: true
  value: "12345678901234567890"
- description: Mongodb service name
  displayName: Mongodb service name
  name: MONGODB_SERVICE_NAME
  required: true
  value: "mongodb-internal"
