apiVersion: v1
kind: Template
metadata:
  name: mongodb-persistent-replicaset
objects:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: "mongodb"
  spec:
    serviceName: "mongodb"
    replicas: 3
    template:
      metadata:
        labels:
          name: "mongodb"
      spec:
        containers:
          - name: mongo-container
            image: "registry.access.redhat.com/rhscl/mongodb-32-rhel7:3.2"
            ports:
              - containerPort: 27017
            args:
              - "run-mongod-replication"
            volumeMounts:
              - name: mongo-data
                mountPath: "/var/lib/mongodb/data"
            env:
              - name: MONGODB_DATABASE
                valueFrom:
                  configMapKeyRef:
                    key: database-name
                    name: mongodb-configmap
              - name: MONGODB_USER
                valueFrom:
                  configMapKeyRef:
                    key: database-user
                    name: mongodb-configmap
              - name: MONGODB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    key: database-password
                    name: mongodb-configmap
              - name: MONGODB_ADMIN_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    key: database-admin-password
                    name: mongodb-configmap
              - name: MONGODB_REPLICA_NAME
                valueFrom:
                  configMapKeyRef:
                    key: database-rs
                    name: mongodb-configmap
              - name: MONGODB_KEYFILE_VALUE
                valueFrom:
                  configMapKeyRef:
                    key: database-keyfile
                    name: mongodb-configmap
              - name: MONGODB_SERVICE_NAME
                valueFrom:
                  configMapKeyRef:
                    key: service-name
                    name: mongodb-configmap
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: mongo-data
          labels:
            name: "mongodb"
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: 5Gi
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    labels:
      name: "mongodb"
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    clusterIP: None
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: "mongodb"
